project:
  name: quickstart-lenses
  package_lambda: false
  s3_bucket: ''
  regions:
    - eu-west-1
tests:
  default:
    template: templates/main.template.yaml
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      LensesWebIngressCIDR: "0.0.0.0/0"
      LensesSSHIngressCIDR: "0.0.0.0/0"
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
